MAJOR_ARCANA = [
    "The Fool",
    "The Magician",
    "The High Priestess",
    "The Empress",
    "The Emperor",
    "The Hierophant",
    "The Lovers",
    "The Chariot",
    "Strength",
    "The Hermit",
    "Wheel of Fortune",
    "Justice",
    "The Hanged Man",
    "Death",
    "Temperance",
    "The Devil",
    "The Tower",
    "The Star",
    "The Moon",
    "The Sun",
    "Judgement",
    "The World",
]

MINOR_ARCANA = [
    "The Ace of Wands",
    "The Two of Wands",
    "The Three of Wands",
    "The Four of Wands",
    "The Five of Wands",
    "The Six of Wands",
    "The Seven of Wands",
    "The Eight of Wands",
    "The Nine of Wands",
    "The Ten of Wands",
    "The Page of Wands",
    "The Knight of Wands",
    "The Queen of Wands",
    "The King of Wands",
    "The Ace of Swords",
    "The Two of Swords",
    "The Three of Swords",
    "The Four of Swords",
    "The Five of Swords",
    "The Six of Swords",
    "The Seven of Swords",
    "The Eight of Swords",
    "The Nine of Swords",
    "The Ten of Swords",
    "The Page of Swords",
    "The Knight of Swords",
    "The Queen of Swords",
    "The King of Swords",
    "The Ace of Cups",
    "The Two of Cups",
    "The Three of Cups",
    "The Four of Cups",
    "The Five of Cups",
    "The Six of Cups",
    "The Seven of Cups",
    "The Eight of Cups",
    "The Nine of Cups",
    "The Ten of Cups",
    "The Page of Cups",
    "The Knight of Cups",
    "The Queen of Cups",
    "The King of Cups",
    "The Ace of Pentacles",
    "The Two of Pentacles",
    "The Three of Pentacles",
    "The Four of Pentacles",
    "The Five of Pentacles",
    "The Six of Pentacles",
    "The Seven of Pentacles",
    "The Eight of Pentacles",
    "The Nine of Pentacles",
    "The Ten of Pentacles",
    "The Page of Pentacles",
    "The Knight of Pentacles",
    "The Queen of Pentacles",
    "The King of Pentacles",
]

BCAD_MAJOR_ARCANA = {
    "base_url": "https://bcad-major-arcana.s3.amazonaws.com/",
    "cards": {
        "The Fool": {"fname": "The+Fool.png"},
        "The Magician": {"fname": "The+Magician.png"},
        "The High Priestess": {"fname": "The+High+Priestess.png"},
        "The Empress": {"fname": "The+Empress.png"},
        "The Emperor": {"fname": "The+Emperor.png"},
        "The Hierophant": {"fname": "The+Hierophant.png"},
        "The Lovers": {"fname": "The+Lovers.png"},
        "The Chariot": {"fname": "The+Chariot.png"},
        "Strength": {"fname": "Strength.png"},
        "The Hermit": {"fname": "The+Hermit.png"},
        "Wheel of Fortune": {"fname": "Wheel+of+Fortune.png"},
        "Justice": {"fname": "Justice.png"},
        "The Hanged Man": {"fname": "The+Hanged+Man.png"},
        "Death": {"fname": "Death.png"},
        "Temperance": {"fname": "Temperance.png"},
        "The Devil": {"fname": "The+Devil.png"},
        "The Tower": {"fname": "The+Tower.png"},
        "The Star": {"fname": "The+Star.png"},
        "The Moon": {"fname": "The+Moon.png"},
        "The Sun": {"fname": "The+Sun.png"},
        "Judgement": {"fname": "Judgement.png"},
        "The World": {"fname": "The+World.png"},
    }
}

ABRAHAM_TAROT = {
    "base_url": "https://abraham-tarot.s3.us-west-1.amazonaws.com/",
    "cards": {
        "The Fool": {"fname": "0SolarPunkFool.jpg"},
        "The Magician": {"fname": "1SolarPunkTheMagician1.jpg"},
        "The High Priestess": {"fname": "2SolarPunkThe+High+Priestess.jpg"},
        "The Empress": {"fname": "3SolarPunkTheEmpress.jpg"},
        "The Emperor": {"fname": "4SolarPunkTheEmperor.jpg"},
        "The Hierophant": {"fname": "5SolarPunkHeirophant.jpg"},
        "The Lovers": {"fname": "6SolarPunkLovers2.jpg"},
        "The Chariot": {"fname": "7SolarPunkChariot.jpg"},
        "Strength": {"fname": "8SolarPunkStrength+copy.jpg"},
        "The Hermit": {"fname": "9SolarPunkHermit.jpg"},
        "Wheel of Fortune": {"fname": "10SolarPunkFortune3.jpg"},
        "Justice": {"fname": "11SolarPunkJustice.png"},
        "The Hanged Man": {"fname": "12SolarPunkHangedMan.png"},
        "Death": {"fname": "13SolarPunkDeath.jpg"},
        "Temperance": {"fname": "14SolarPunkTemperance.jpg"},
        "The Devil": {"fname": "15SolarPunkDevil.jpg"},
        "The Tower": {"fname": "16SolarPunkTower.jpg"},
        "The Star": {"fname": "17SolarPunkStar.jpg"},
        "The Moon": {"fname": "18SolarPunkMoon.png"},
        "The Sun": {"fname": "19SolarPunkSun.jpg"},
        "Judgement": {"fname": "20SolarPunkJudgement.jpg"},
        "The World": {"fname": "21SolarPunkWorld.png"},
        "The Ace of Wands": {"fname": "1Ace+of+Rods+Chillwave.png"},
        "The Two of Wands": {"fname": "2Two+of+Chillwave+with+Two+wands.png"},
        "The Three of Wands": {"fname": "3Three+of+Chillwave+with+Three+wands.png"},
        "The Four of Wands": {"fname": "4Four+of+Rods+Chillwave.png"},
        "The Five of Wands": {"fname": "5Five+of+Rods+Chillwave.png"},
        "The Six of Wands": {"fname": "6Six+of+Chillwave+with+six+wands.png"},
        "The Seven of Wands": {"fname": "7Seven+of+Chillwave+with+a+wand.png"},
        "The Eight of Wands": {"fname": "8Eight+of+Rods+Chillwave.png"},
        "The Nine of Wands": {"fname": "9Nine+of+Chillwave+with+a+wand.png"},
        "The Ten of Wands": {"fname": "10Ten+of+Rods+Chillwave.png"},
        "The Page of Wands": {"fname": "11Maiden+of+Chillwave+with+a+wand.png"},
        "The Knight of Wands": {"fname": "12Young+Man+of+Chillwave+with+a+wand.png"},
        "The Queen of Wands": {"fname": "13Queen+of+Chillwave+with+a+wand.png"},
        "The King of Wands": {"fname": "14King+of+Chillwave.png"},
        "The Ace of Swords": {"fname": "1Ace+of+Swords+Retrowave.png"},
        "The Two of Swords": {"fname": "2Two+of+Retrowaves+with+swords.png"},
        "The Three of Swords": {"fname": "3Three+of+Retrowaves+with+Swords.png"},
        "The Four of Swords": {"fname": "4Four+of+Retrowaves+with+swords.png"},
        "The Five of Swords": {"fname": "5Five+of+Retrowaves+with+swords.png"},
        "The Six of Swords": {"fname": "6Six+of+Retrowaves+with+swords.png"},
        "The Seven of Swords": {"fname": "7Seven+of+Retrowaves+with+swords.png"},
        "The Eight of Swords": {"fname": "8Eight+of+Retrowaves+with+swords.png"},
        "The Nine of Swords": {"fname": "9Nine+of+Retrowaves+with+swords.png"},
        "The Ten of Swords": {"fname": "10Ten+of+Retrowaves+with+swords.png"},
        "The Page of Swords": {"fname": "11Maiden+of+Retrowaves+holding+a+sword.png"},
        "The Knight of Swords": {"fname": "12Knight+of+Retrowaves+holding+a+sword.png"},
        "The Queen of Swords": {"fname": "13Queen+of+Retrowaves+with+a+Sword.png"},
        "The King of Swords": {"fname": "14King+of+Retrowaves+with+a+sword.png"},
        "The Ace of Cups": {"fname": "1AceofCups.png"},
        "The Two of Cups": {"fname": "2+of+cups+psychedelic+neon+copy.png"},
        "The Three of Cups": {"fname": "3ThreeofCupsWeirdcorePsychedelic2.png"},
        "The Four of Cups": {"fname": "4+of+cups+copy.png"},
        "The Five of Cups": {"fname": "5+of+cups+copy.png"},
        "The Six of Cups": {"fname": "6+of+cups+copy.png"},
        "The Seven of Cups": {"fname": "7+of+cups+copy.png"},
        "The Eight of Cups": {"fname": "8+of+cups+copy.png"},
        "The Nine of Cups": {"fname": "9+of+cups+copy.png"},
        "The Ten of Cups": {"fname": "10+of+cups2+copy.png"},
        "The Page of Cups": {"fname": "11+Maiden+of+Cups.jpg"},
        "The Knight of Cups": {"fname": "12Youth+of+cups+psychedelic+neon+copy.jpg"},
        "The Queen of Cups": {"fname": "13Queen+of+cups+psychedelic+neon.jpg"},
        "The King of Cups": {"fname": "14King+of+cups+psychedelic+neon.jpg"},
        "The Ace of Pentacles": {"fname": "1Ace+of+cyber+glitch+with+one+pentacle.jpg"},
        "The Two of Pentacles": {
            "fname": "2Two+of+cyber+glitch+with+two+pentacles-Recovered+copy.jpg"
        },
        "The Three of Pentacles": {
            "fname": "3Five+of+cyber+glitch+with+five+pentagram-coins-Recovered+copy.jpg"
        },
        "The Four of Pentacles": {
            "fname": "4four+of+glitch+core+with+four+pentacles-Recovered+copy.jpg"
        },
        "The Five of Pentacles": {
            "fname": "5Five+of+cyber+glitch+with+five+pentagrams-Recovered+copy.jpg"
        },
        "The Six of Pentacles": {
            "fname": "6six+of+cyber+glitch+with+six+pentagrams-Recovered+copy.jpg"
        },
        "The Seven of Pentacles": {
            "fname": "7nine+of+glitch+core+with+nine+pentacles-Recovered+copy.jpg"
        },
        "The Eight of Pentacles": {
            "fname": "8eight+of+glitchcore+with+eight+pentacles+copy-Recovered+copy.jpg"
        },
        "The Nine of Pentacles": {
            "fname": "9nine+of+glitchcore+with+nine+pentacles-Recovered+copy.jpg"
        },
        "The Ten of Pentacles": {
            "fname": "10Five+of+cyber+glitch+with+five+coins-Recovered+copy.jpg"
        },
        "The Page of Pentacles": {
            "fname": "11maiden+of+computer+glitch+with+pentagram+cyber-Recovered+copy.jpg"
        },
        "The Knight of Pentacles": {
            "fname": "12glitch+core+queen+with+a+pentacle-Recovered+copy.jpg"
        },
        "The Queen of Pentacles": {
            "fname": "13glitch+core+queen+with+pentacle-Recovered+copy.jpg"
        },
        "The King of Pentacles": {
            "fname": "14king+of+computer+glitch+with+pentagram-Recovered+copy.jpg"
        },
    },
}